- id: cycode
  name: Cycode pre commit defender
  language: python
  entry: cycode
  args: [ 'scan', 'pre_commit' ]
- id: cycode-sca
  name: Cycode SCA pre commit defender
  language: python
  entry: cycode
  args: [ 'scan', '-t', 'sca', 'pre_commit' ]