- id: cycode
  name: Cycode pre commit defender
  language: python
  language_version: python3
  entry: cycode
  args: [ '--no-progress-meter', 'scan', 'pre_commit' ]
- id: cycode-sca
  name: Cycode SCA pre commit defender
  language: python
  language_version: python3
  entry: cycode
  args: [ '--no-progress-meter', 'scan', '--scan-type', 'sca', 'pre_commit' ]
