- id: cycode
  name: Cycode Secrets pre-commit defender
  language: python
  language_version: python3
  entry: cycode
  args: [ '--no-progress-meter', 'scan', '--scan-type', 'secret', 'pre-commit' ]
- id: cycode-sca
  name: Cycode SCA pre-commit defender
  language: python
  language_version: python3
  entry: cycode
  args: [ '--no-progress-meter', 'scan', '--scan-type', 'sca', 'pre-commit' ]
