from pathlib import Path
from typing import Optional
from unittest.mock import MagicMock, patch

import pytest
import typer

from cycode.cli.files_collector.sca.php.restore_composer_dependencies import (
    COMPOSER_LOCK_FILE_NAME,
    RestoreComposerDependencies,
)
from cycode.cli.models import Document


@pytest.fixture
def mock_ctx(tmp_path: Path) -> typer.Context:
    ctx = MagicMock(spec=typer.Context)
    ctx.obj = {'monitor': False}
    ctx.params = {'path': str(tmp_path)}
    return ctx


@pytest.fixture
def restore_composer(mock_ctx: typer.Context) -> RestoreComposerDependencies:
    return RestoreComposerDependencies(mock_ctx, is_git_diff=False, command_timeout=30)


class TestIsProject:
    def test_composer_json_matches(self, restore_composer: RestoreComposerDependencies) -> None:
        doc = Document('composer.json', '{"name": "vendor/project"}\n')
        assert restore_composer.is_project(doc) is True

    def test_composer_json_in_subdir_matches(self, restore_composer: RestoreComposerDependencies) -> None:
        doc = Document('myapp/composer.json', '{"name": "vendor/project"}\n')
        assert restore_composer.is_project(doc) is True

    def test_composer_lock_does_not_match(self, restore_composer: RestoreComposerDependencies) -> None:
        doc = Document('composer.lock', '{"_readme": []}\n')
        assert restore_composer.is_project(doc) is False

    def test_package_json_does_not_match(self, restore_composer: RestoreComposerDependencies) -> None:
        doc = Document('package.json', '{"name": "test"}\n')
        assert restore_composer.is_project(doc) is False

    def test_other_json_does_not_match(self, restore_composer: RestoreComposerDependencies) -> None:
        doc = Document('config.json', '{"setting": "value"}\n')
        assert restore_composer.is_project(doc) is False


class TestTryRestoreDependencies:
    def test_existing_composer_lock_returned_directly(
        self, restore_composer: RestoreComposerDependencies, tmp_path: Path
    ) -> None:
        lock_content = '{\n    "_readme": ["This file is @generated by Composer"],\n    "packages": []\n}\n'
        (tmp_path / 'composer.json').write_text('{"name": "vendor/project"}\n')
        (tmp_path / 'composer.lock').write_text(lock_content)

        doc = Document(
            str(tmp_path / 'composer.json'),
            '{"name": "vendor/project"}\n',
            absolute_path=str(tmp_path / 'composer.json'),
        )
        result = restore_composer.try_restore_dependencies(doc)

        assert result is not None
        assert COMPOSER_LOCK_FILE_NAME in result.path
        assert result.content == lock_content

    def test_get_lock_file_name(self, restore_composer: RestoreComposerDependencies) -> None:
        assert restore_composer.get_lock_file_name() == COMPOSER_LOCK_FILE_NAME

_BASE_MODULE = 'cycode.cli.files_collector.sca.base_restore_dependencies'


class TestCleanup:
    def test_generated_lockfile_is_deleted_after_restore(
        self, restore_composer: RestoreComposerDependencies, tmp_path: Path
    ) -> None:
        manifest_content = '{"name": "vendor/project"}\n'
        (tmp_path / 'composer.json').write_text(manifest_content)
        doc = Document(
            str(tmp_path / 'composer.json'), manifest_content, absolute_path=str(tmp_path / 'composer.json')
        )
        lock_path = tmp_path / COMPOSER_LOCK_FILE_NAME

        def side_effect(
            commands: list, timeout: int, output_file_path: Optional[str] = None, working_directory: Optional[str] = None
        ) -> str:
            lock_path.write_text('{"_readme": [], "packages": []}')
            return 'output'

        with patch(f'{_BASE_MODULE}.execute_commands', side_effect=side_effect):
            result = restore_composer.try_restore_dependencies(doc)

        assert result is not None
        assert not lock_path.exists(), f'{COMPOSER_LOCK_FILE_NAME} must be deleted after restore'

    def test_preexisting_lockfile_is_not_deleted(
        self, restore_composer: RestoreComposerDependencies, tmp_path: Path
    ) -> None:
        lock_content = '{\n    "_readme": ["This file is @generated by Composer"],\n    "packages": []\n}\n'
        (tmp_path / 'composer.json').write_text('{"name": "vendor/project"}\n')
        lock_path = tmp_path / COMPOSER_LOCK_FILE_NAME
        lock_path.write_text(lock_content)
        doc = Document(
            str(tmp_path / 'composer.json'),
            '{"name": "vendor/project"}\n',
            absolute_path=str(tmp_path / 'composer.json'),
        )

        result = restore_composer.try_restore_dependencies(doc)

        assert result is not None
        assert lock_path.exists(), f'Pre-existing {COMPOSER_LOCK_FILE_NAME} must not be deleted'


class TestGetCommands:
    def test_get_commands_returns_composer_update(self, restore_composer: RestoreComposerDependencies) -> None:
        commands = restore_composer.get_commands('/path/to/composer.json')
        assert commands == [
            [
                'composer',
                'update',
                '--no-cache',
                '--no-install',
                '--no-scripts',
                '--ignore-platform-reqs',
            ]
        ]
