soft_fail: False
scans:
  supported_scans:
    - secret
    - iac
    - sca
    - sast
  supported_sca_scans:
    - package-vulnerabilities
    - license-compliance
  supported_sbom_formats:
    - spdx-2.2
    - spdx-2.3
    - cyclonedx-1.4
result_printer:
  default:
    lines_to_display: 3
    show_secret: False
  secret:
    pre_receive:
      lines_to_display: 1
      show_secret: False
    commit_history:
      lines_to_display: 1
      show_secret: False