"""Tests for BaseRestoreDependencies cleanup behavior.

Verifies that lock files generated by restore commands are deleted after
scanning, while pre-existing lock files are left untouched.
"""

from pathlib import Path
from typing import Optional
from unittest.mock import MagicMock, patch

import pytest
import typer

from cycode.cli.files_collector.sca.base_restore_dependencies import BaseRestoreDependencies
from cycode.cli.models import Document

_LOCK_FILE_NAME = 'generated.lock'
_MANIFEST_FILE_NAME = 'manifest.txt'
_LOCK_CONTENT = 'generated lock content'

_BASE_MODULE = 'cycode.cli.files_collector.sca.base_restore_dependencies'


class _MinimalRestoreHandler(BaseRestoreDependencies):
    """Minimal concrete subclass for directly testing BaseRestoreDependencies."""

    def is_project(self, document: Document) -> bool:
        return document.path.endswith(_MANIFEST_FILE_NAME)

    def get_commands(self, manifest_file_path: str) -> list[list[str]]:
        return [['echo', 'fake']]

    def get_lock_file_name(self) -> str:
        return _LOCK_FILE_NAME

    def get_lock_file_names(self) -> list[str]:
        return [_LOCK_FILE_NAME]


@pytest.fixture
def mock_ctx(tmp_path: Path) -> typer.Context:
    ctx = MagicMock(spec=typer.Context)
    ctx.obj = {'monitor': False}
    ctx.params = {'path': str(tmp_path)}
    return ctx


@pytest.fixture
def handler(mock_ctx: typer.Context) -> _MinimalRestoreHandler:
    return _MinimalRestoreHandler(mock_ctx, is_git_diff=False, command_timeout=30)


def _make_doc(tmp_path: Path) -> Document:
    manifest = tmp_path / _MANIFEST_FILE_NAME
    manifest.write_text('content')
    return Document(str(manifest), 'content', absolute_path=str(manifest))


def _make_execute_side_effect(lock_path: Path, content: str = _LOCK_CONTENT) -> object:
    """Returns an execute_commands side_effect that writes the lock file."""

    def side_effect(
        commands: list, timeout: int, output_file_path: Optional[str] = None, working_directory: Optional[str] = None
    ) -> str:
        lock_path.write_text(content)
        return 'output'

    return side_effect


class TestCleanupGeneratedFile:
    def test_generated_lockfile_is_deleted_after_restore(self, handler: _MinimalRestoreHandler, tmp_path: Path) -> None:
        doc = _make_doc(tmp_path)
        lock_path = tmp_path / _LOCK_FILE_NAME

        with patch(f'{_BASE_MODULE}.execute_commands', side_effect=_make_execute_side_effect(lock_path)):
            result = handler.try_restore_dependencies(doc)

        assert result is not None
        assert result.content == _LOCK_CONTENT
        assert not lock_path.exists(), 'Generated lock file must be deleted after restore'

    def test_preexisting_lockfile_is_not_deleted(self, handler: _MinimalRestoreHandler, tmp_path: Path) -> None:
        doc = _make_doc(tmp_path)
        lock_path = tmp_path / _LOCK_FILE_NAME
        lock_path.write_text('pre-existing content')

        result = handler.try_restore_dependencies(doc)

        assert result is not None
        assert result.content == 'pre-existing content'
        assert lock_path.exists(), 'Pre-existing lock file must not be deleted'

    def test_returned_document_content_matches_generated_file(
        self, handler: _MinimalRestoreHandler, tmp_path: Path
    ) -> None:
        doc = _make_doc(tmp_path)
        expected = '{"dependencies": {"requests": "^2.31"}}'
        lock_path = tmp_path / _LOCK_FILE_NAME

        with patch(f'{_BASE_MODULE}.execute_commands', side_effect=_make_execute_side_effect(lock_path, expected)):
            result = handler.try_restore_dependencies(doc)

        assert result is not None
        assert result.content == expected

    def test_cleanup_does_not_raise_when_generated_file_missing(
        self, handler: _MinimalRestoreHandler, tmp_path: Path
    ) -> None:
        """unlink(missing_ok=True) must not raise even if the command didn't create the file."""
        doc = _make_doc(tmp_path)

        def side_effect(**_kwargs: object) -> str:
            return 'output'  # returned non-None but didn't create the file

        with patch(f'{_BASE_MODULE}.execute_commands', side_effect=side_effect):
            result = handler.try_restore_dependencies(doc)

        # File was never created; content is None but no exception raised
        assert result is not None
        assert result.content is None

    def test_failed_command_returns_none_and_no_file_created(
        self, handler: _MinimalRestoreHandler, tmp_path: Path
    ) -> None:
        doc = _make_doc(tmp_path)
        lock_path = tmp_path / _LOCK_FILE_NAME

        with patch(f'{_BASE_MODULE}.execute_commands', return_value=None):
            result = handler.try_restore_dependencies(doc)

        assert result is None
        assert not lock_path.exists()

    def test_generated_file_content_available_in_document_after_deletion(
        self, handler: _MinimalRestoreHandler, tmp_path: Path
    ) -> None:
        """The Document must carry the file content even after the file is removed."""
        doc = _make_doc(tmp_path)
        lock_path = tmp_path / _LOCK_FILE_NAME
        expected = 'important scan data'

        with patch(f'{_BASE_MODULE}.execute_commands', side_effect=_make_execute_side_effect(lock_path, expected)):
            result = handler.try_restore_dependencies(doc)

        assert not lock_path.exists()
        assert result is not None
        assert result.content == expected
