"""Archive builders for the binary-extraction suite.

Every fixture is *built* at test time into ``tmp_path``. Nothing binary is committed: CI runs with no network egress
so a downloaded artifact would fail there even where it passes locally, and committing hostile archives into a
security product's own repository is a problem of its own. The upside is that each hostile case reads as code.
"""

import io
import zipfile
from typing import Optional, Union

# ZipInfo.external_attr carries the unix mode in its high 16 bits
REGULAR_FILE_ATTR = 0o100644 << 16
SYMLINK_ATTR = 0o120777 << 16
DIRECTORY_ATTR = 0o040755 << 16
FIFO_ATTR = 0o010644 << 16

# an archive written by MS-DOS tooling records no unix mode at all
MSDOS_ATTR = 0

_Contents = dict[str, Union[bytes, str]]


def archive_bytes(
    files: Optional[_Contents] = None,
    symlinks: Optional[dict[str, str]] = None,
    external_attrs: Optional[dict[str, int]] = None,
    compress: bool = True,
) -> bytes:
    """Build an archive in memory.

    ``files`` maps entry name to content. ``symlinks`` maps entry name to link target, written with the unix mode
    bits that mark it a symlink. ``external_attrs`` overrides the mode for a named entry.
    """
    files = files or {}
    symlinks = symlinks or {}
    external_attrs = external_attrs or {}
    compress_type = zipfile.ZIP_DEFLATED if compress else zipfile.ZIP_STORED

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w', compress_type) as archive:
        for name, content in files.items():
            info = zipfile.ZipInfo(name)
            info.compress_type = compress_type
            info.external_attr = external_attrs.get(name, REGULAR_FILE_ATTR)
            archive.writestr(info, content)

        for name, target in symlinks.items():
            info = zipfile.ZipInfo(name)
            info.compress_type = compress_type
            info.external_attr = SYMLINK_ATTR
            archive.writestr(info, target)

    return buffer.getvalue()


def pom_properties(group: str, artifact: str, version: str) -> str:
    return f'#Generated by Maven\ngroupId={group}\nartifactId={artifact}\nversion={version}\n'


def pom_properties_entry_name(group: str, artifact: str) -> str:
    return f'META-INF/maven/{group}/{artifact}/pom.properties'


def manifest(**attributes: str) -> str:
    lines = ['Manifest-Version: 1.0']
    lines.extend(f'{key.replace("_", "-")}: {value}' for key, value in attributes.items())
    return '\n'.join(lines) + '\n'


def library_jar(group: str, artifact: str, version: str) -> bytes:
    """A jar that identifies itself the way a Maven-built artifact does."""
    return archive_bytes(
        files={
            'META-INF/MANIFEST.MF': manifest(Implementation_Title=artifact, Implementation_Version=version),
            pom_properties_entry_name(group, artifact): pom_properties(group, artifact, version),
            f'{group.replace(".", "/")}/{artifact}/Main.class': b'\xca\xfe\xba\xbe fake class bytes',
        }
    )


def war_bytes(libraries: Optional[dict[str, bytes]] = None) -> bytes:
    """A WAR with its libraries under ``WEB-INF/lib``."""
    files: _Contents = {
        'WEB-INF/web.xml': '<web-app/>',
        'index.jsp': '<html></html>',
    }
    for name, content in (libraries or {}).items():
        files[f'WEB-INF/lib/{name}'] = content

    return archive_bytes(files=files)


def boot_jar_bytes(libraries: Optional[dict[str, bytes]] = None) -> bytes:
    """A Spring Boot fat JAR, whose libraries live under ``BOOT-INF/lib``."""
    files: _Contents = {
        'META-INF/MANIFEST.MF': manifest(Main_Class='org.springframework.boot.loader.JarLauncher'),
        'BOOT-INF/classes/com/acme/App.class': b'\xca\xfe\xba\xbe',
    }
    for name, content in (libraries or {}).items():
        files[f'BOOT-INF/lib/{name}'] = content

    return archive_bytes(files=files)


def ear_bytes(modules: Optional[dict[str, bytes]] = None, libraries: Optional[dict[str, bytes]] = None) -> bytes:
    """An EAR whose modules sit at its root, as ``application.xml`` would declare them."""
    files: _Contents = {'META-INF/application.xml': '<application/>'}
    files.update(modules or {})
    for name, content in (libraries or {}).items():
        files[f'APP-INF/lib/{name}'] = content

    return archive_bytes(files=files)


# --- hostile corpus ---------------------------------------------------------------------------------------------


def zip_slip_bytes(name: str = '../../evil.txt') -> bytes:
    return archive_bytes(files={'harmless.txt': 'ok', name: 'owned'})


def absolute_path_bytes() -> bytes:
    return archive_bytes(files={'/etc/passwd': 'root:x:0:0:'})


def drive_letter_bytes() -> bytes:
    return archive_bytes(files={'C:\\Windows\\System32\\evil.dll': 'owned'})


def unc_path_bytes() -> bytes:
    return archive_bytes(files={'\\\\host\\share\\evil.txt': 'owned'})


def reserved_name_bytes(name: str = 'CON') -> bytes:
    return archive_bytes(files={name: 'owned'})


def symlink_bytes() -> bytes:
    return archive_bytes(files={'real.txt': 'ok'}, symlinks={'escape.txt': '/etc/passwd'})


def non_regular_entry_bytes() -> bytes:
    return archive_bytes(files={'fifo': '', 'real.txt': 'ok'}, external_attrs={'fifo': FIFO_ATTR})


def msdos_created_bytes() -> bytes:
    """An archive with no unix mode recorded at all, as produced by Windows tooling. Must still be readable."""
    return archive_bytes(files={'real.txt': 'ok'}, external_attrs={'real.txt': MSDOS_ATTR})


def ratio_bomb_bytes(uncompressed_size: int = 4 * 1024 * 1024) -> bytes:
    """Highly compressible payload: a few kilobytes on disk, megabytes once read."""
    return archive_bytes(files={'bomb.bin': b'\x00' * uncompressed_size})


def size_bomb_bytes(uncompressed_size: int = 64 * 1024) -> bytes:
    """A single entry larger than a deliberately small per-entry cap."""
    return archive_bytes(files={'big.bin': b'A' * uncompressed_size}, compress=False)


def total_size_bomb_bytes(entry_count: int = 8, entry_size: int = 16 * 1024) -> bytes:
    """Several modest entries that only breach the cap in aggregate."""
    return archive_bytes(
        files={f'part-{index}.bin': b'B' * entry_size for index in range(entry_count)},
        compress=False,
    )


def count_bomb_bytes(entry_count: int) -> bytes:
    return archive_bytes(files={f'entry-{index}.txt': '' for index in range(entry_count)})


def empty_archive_bytes() -> bytes:
    return archive_bytes()


def not_a_zip_bytes() -> bytes:
    return b'this is not a zip file, it merely has the name of one' * 8


def truncated_central_directory_bytes() -> bytes:
    """A valid archive with its tail lopped off, so the central directory can never be located."""
    valid = archive_bytes(files={'a.txt': 'a' * 512, 'b.txt': 'b' * 512})
    return valid[: len(valid) // 2]


def malformed_local_header_bytes() -> bytes:
    """Central directory intact, local file header corrupted: opens cleanly, fails on read."""
    valid = bytearray(archive_bytes(files={'a.txt': 'a' * 512}))
    signature_offset = valid.find(b'PK\x03\x04')
    assert signature_offset != -1
    valid[signature_offset : signature_offset + 4] = b'XXXX'
    return bytes(valid)
