import pytest

from cycode.cli.files_collector.binary.identifiers import manifest_mf, pom_properties, pom_xml
from cycode.cli.files_collector.binary.identifiers.pom_xml import UnsafeXmlError

_POM_NAMESPACE = 'http://maven.apache.org/POM/4.0.0'


class TestPomProperties:
    def test_a_maven_written_file(self) -> None:
        payload = (
            b'#Generated by Maven\n'
            b'#Mon Aug 26 12:00:00 UTC 2026\n'
            b'groupId=com.google.guava\n'
            b'artifactId=guava\n'
            b'version=31.1-jre\n'
        )

        coordinates = pom_properties.identify(payload)

        assert coordinates.group == 'com.google.guava'
        assert coordinates.artifact == 'guava'
        assert coordinates.version == '31.1-jre'

    def test_colon_separator_and_surrounding_whitespace(self) -> None:
        payload = b'groupId : com.acme \nartifactId:  widget\nversion:\t2.0\n'

        coordinates = pom_properties.identify(payload)

        assert (coordinates.group, coordinates.artifact, coordinates.version) == ('com.acme', 'widget', '2.0')

    def test_a_byte_order_mark_is_tolerated(self) -> None:
        payload = '﻿groupId=com.acme\nartifactId=widget\nversion=1.0\n'.encode()

        assert pom_properties.identify(payload).group == 'com.acme'

    @pytest.mark.parametrize(
        'payload',
        [
            b'groupId=com.acme\nartifactId=widget\n',  # no version
            b'artifactId=widget\nversion=1.0\n',  # no group
            b'groupId=com.acme\nversion=1.0\n',  # no artifact
            b'',
            b'# nothing but a comment\n',
            b'! bang comments are comments too\n',
        ],
    )
    def test_an_incomplete_set_identifies_nothing(self, payload: bytes) -> None:
        assert pom_properties.identify(payload) is None

    def test_undecodable_bytes_do_not_raise(self) -> None:
        # one malformed file must not fail the scan of an entire deployable
        assert pom_properties.identify(b'\xff\xfe\x00garbage') is None


class TestManifest:
    def test_implementation_attributes(self) -> None:
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: log4j-core\n'
            b'Implementation-Version: 2.14.1\n'
            b'Implementation-Vendor-Id: org.apache.logging.log4j\n'
        )

        identity = manifest_mf.identify(payload)

        assert identity.coordinates.artifact == 'log4j-core'
        assert identity.coordinates.version == '2.14.1'
        # a declared vendor id is a declared group id, not an inference
        assert identity.coordinates.group == 'org.apache.logging.log4j'
        assert identity.source_attribute == manifest_mf.IMPLEMENTATION_TITLE

    def test_a_line_wrapped_at_seventy_two_bytes_is_rejoined(self) -> None:
        # the format wraps at 72 bytes and continues with a leading single space
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: org.eclipse.jetty.util.some.very.lon\n'
            b' g.artifact.name\n'
            b'Implementation-Version: 9.4.44\n'
            b'Implementation-Vendor-Id: org.eclipse.jetty\n'
        )

        identity = manifest_mf.identify(payload)

        assert identity.coordinates.artifact == 'org.eclipse.jetty.util.some.very.long.artifact.name'

    def test_a_multibyte_character_split_across_the_wrap(self) -> None:
        # the wrap counts bytes, not characters, so continuation must be joined before decoding
        value = 'café-parser'
        encoded = value.encode('utf-8')
        split_at = encoded.index(b'\xc3') + 1  # mid-character
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: ' + encoded[:split_at] + b'\n ' + encoded[split_at:] + b'\n'
            b'Implementation-Version: 1.0\n'
            b'Implementation-Vendor-Id: com.acme\n'
        )

        attributes = manifest_mf.parse_manifest(payload)

        assert attributes[manifest_mf.IMPLEMENTATION_TITLE] == value

    def test_carriage_returns_are_handled(self) -> None:
        payload = (
            b'Manifest-Version: 1.0\r\nImplementation-Title: widget\r\nImplementation-Version: 1.0\r\n'
            b'Implementation-Vendor-Id: com.acme\r\n'
        )

        assert manifest_mf.identify(payload).coordinates.artifact == 'widget'

    def test_only_the_main_section_is_read(self) -> None:
        # per-entry sections describe individual files, not the artifact
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: real-artifact\n'
            b'Implementation-Version: 1.0\n'
            b'Implementation-Vendor-Id: com.acme\n'
            b'\n'
            b'Name: com/acme/Other.class\n'
            b'Implementation-Title: not-the-artifact\n'
            b'Implementation-Version: 9.9\n'
        )

        assert manifest_mf.identify(payload).coordinates.artifact == 'real-artifact'

    def test_osgi_bundle_attributes_are_the_fallback(self) -> None:
        payload = (
            b'Manifest-Version: 1.0\nBundle-SymbolicName: com.acme.thing;singleton:=true\nBundle-Version: 3.1.0\n'
            b'Implementation-Vendor-Id: com.acme\n'
        )

        identity = manifest_mf.identify(payload)

        # directives are not part of the name
        assert identity.coordinates.artifact == 'com.acme.thing'
        assert identity.coordinates.version == '3.1.0'
        assert identity.source_attribute == manifest_mf.BUNDLE_SYMBOLIC_NAME

    def test_automatic_module_name_is_the_last_resort(self) -> None:
        payload = (
            b'Manifest-Version: 1.0\nAutomatic-Module-Name: com.acme.widget\nImplementation-Version: 4.2\n'
            b'Implementation-Vendor-Id: com.acme\n'
        )

        identity = manifest_mf.identify(payload)

        assert identity.coordinates.artifact == 'com.acme.widget'
        assert identity.source_attribute == manifest_mf.AUTOMATIC_MODULE_NAME

    def test_no_group_means_no_coordinate(self) -> None:
        # a purl with no namespace matches nothing, so it is not a low-confidence answer, it is noise
        payload = b'Manifest-Version: 1.0\nImplementation-Title: widget\nImplementation-Version: 1.0\n'

        assert manifest_mf.identify(payload) is None

    def test_a_product_name_is_not_an_artifact_id_and_falls_through(self) -> None:
        # seen in the wild: activation.jar titles itself after the server it shipped with
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: Sun Java System Application Server\n'
            b'Implementation-Version: 1.1\n'
            b'Implementation-Vendor-Id: com.sun\n'
            b'Bundle-SymbolicName: javax.activation\n'
            b'Bundle-Version: 1.1.0\n'
        )

        identity = manifest_mf.identify(payload)

        assert identity.coordinates.artifact == 'javax.activation'
        assert identity.source_attribute == manifest_mf.BUNDLE_SYMBOLIC_NAME

    def test_a_build_banner_is_not_a_version(self) -> None:
        # seen in the wild: a vendor connector stamps its build time into Implementation-Version
        payload = (
            b'Manifest-Version: 1.0\n'
            b'Implementation-Title: com.sap.conn.jco\n'
            b'Implementation-Version: 20100905 1938 [3.0.6 (2010-08-24)]\n'
            b'Implementation-Vendor-Id: com.sap\n'
        )

        assert manifest_mf.identify(payload) is None

    @pytest.mark.parametrize('version', ['2.14.1', '1.0M10', '9.4.44.v20210927', '3.0.0-SNAPSHOT', '1.13.0', '2'])
    def test_real_version_shapes_are_accepted(self, version: str) -> None:
        assert manifest_mf.is_version_shaped(version)

    @pytest.mark.parametrize('version', ['', 'v1.0', '20100905 1938 [3.0.6]', 'Build 2024-03-01', '1.0 beta'])
    def test_things_that_are_not_versions(self, version: str) -> None:
        assert not manifest_mf.is_version_shaped(version)

    @pytest.mark.parametrize(
        'payload',
        [
            b'Manifest-Version: 1.0\nImplementation-Title: widget\nImplementation-Vendor-Id: a.b\n',  # no version
            b'Manifest-Version: 1.0\nImplementation-Version: 1.0\nImplementation-Vendor-Id: a.b\n',  # no name
            b'Manifest-Version: 1.0\nMain-Class: com.acme.App\n',
            b'Manifest-Version: 1.0\nImplementation-Title: w\nImplementation-Version: 1\nImplementation-Vendor-Id: A B\n',  # noqa: E501
            b'',
        ],
    )
    def test_a_manifest_that_says_nothing_usable(self, payload: bytes) -> None:
        assert manifest_mf.identify(payload) is None


class TestPomXml:
    def test_direct_dependencies(self) -> None:
        payload = b"""<?xml version="1.0" encoding="UTF-8"?>
        <project>
          <dependencies>
            <dependency>
              <groupId>com.google.guava</groupId>
              <artifactId>guava</artifactId>
              <version>31.1-jre</version>
            </dependency>
            <dependency>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-api</artifactId>
            </dependency>
          </dependencies>
        </project>"""

        dependencies = pom_xml.parse_dependencies(payload)

        assert [d.coordinate_key for d in dependencies] == ['com.google.guava:guava', 'org.slf4j:slf4j-api']
        assert dependencies[0].version == '31.1-jre'
        assert dependencies[1].version is None

    def test_the_maven_namespace_is_handled(self) -> None:
        payload = f"""<?xml version="1.0"?>
        <project xmlns="{_POM_NAMESPACE}">
          <dependencies>
            <dependency><groupId>com.acme</groupId><artifactId>widget</artifactId></dependency>
          </dependencies>
        </project>""".encode()

        assert [d.coordinate_key for d in pom_xml.parse_dependencies(payload)] == ['com.acme:widget']

    @pytest.mark.parametrize('scope', ['test', 'provided', 'system', 'TEST'])
    def test_scopes_that_do_not_ship_are_excluded(self, scope: str) -> None:
        payload = f"""<project><dependencies>
            <dependency><groupId>junit</groupId><artifactId>junit</artifactId><scope>{scope}</scope></dependency>
        </dependencies></project>""".encode()

        assert pom_xml.parse_dependencies(payload) == []

    def test_runtime_and_compile_scopes_are_kept(self) -> None:
        payload = b"""<project><dependencies>
            <dependency><groupId>a</groupId><artifactId>b</artifactId><scope>runtime</scope></dependency>
            <dependency><groupId>c</groupId><artifactId>d</artifactId><scope>compile</scope></dependency>
        </dependencies></project>"""

        assert [d.coordinate_key for d in pom_xml.parse_dependencies(payload)] == ['a:b', 'c:d']

    def test_dependency_management_is_not_an_edge(self) -> None:
        # these declare versions for modules that may never be depended on
        payload = b"""<project>
          <dependencyManagement>
            <dependencies>
              <dependency><groupId>managed</groupId><artifactId>only</artifactId><version>1.0</version></dependency>
            </dependencies>
          </dependencyManagement>
          <dependencies>
            <dependency><groupId>real</groupId><artifactId>dep</artifactId></dependency>
          </dependencies>
        </project>"""

        assert [d.coordinate_key for d in pom_xml.parse_dependencies(payload)] == ['real:dep']

    def test_a_pom_with_no_dependencies(self) -> None:
        assert pom_xml.parse_dependencies(b'<project><artifactId>lonely</artifactId></project>') == []


class TestXmlSafety:
    _BILLION_LAUGHS = b"""<?xml version="1.0"?>
    <!DOCTYPE lolz [
     <!ENTITY lol "lol">
     <!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
     <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
    ]>
    <project><artifactId>&lol3;</artifactId></project>"""

    _EXTERNAL_ENTITY = b"""<?xml version="1.0"?>
    <!DOCTYPE project [ <!ENTITY xxe SYSTEM "file:///etc/passwd"> ]>
    <project><artifactId>&xxe;</artifactId></project>"""

    def test_billion_laughs_is_refused_before_parsing(self) -> None:
        with pytest.raises(UnsafeXmlError, match='document type or entity declaration'):
            pom_xml.parse_xml(self._BILLION_LAUGHS)

    def test_external_entity_is_refused_before_parsing(self) -> None:
        with pytest.raises(UnsafeXmlError, match='document type or entity declaration'):
            pom_xml.parse_xml(self._EXTERNAL_ENTITY)

    @pytest.mark.parametrize(
        'payload',
        [
            b'<!doctype project []><project/>',  # lowercase
            b'<!  DOCTYPE project []><project/>',  # spaced
            b'<!ENTITY loose "x">',
        ],
    )
    def test_declarations_are_refused_however_they_are_written(self, payload: bytes) -> None:
        with pytest.raises(UnsafeXmlError):
            pom_xml.parse_xml(payload)

    def test_a_hostile_pom_yields_no_edges_rather_than_raising(self) -> None:
        # one bad pom inside a deployable must not fail the whole scan
        assert pom_xml.parse_dependencies(self._BILLION_LAUGHS) == []

    def test_malformed_xml_yields_no_edges(self) -> None:
        assert pom_xml.parse_dependencies(b'<project><dependencies>') == []

    def test_predefined_entities_still_work(self) -> None:
        payload = b'<project><dependencies><dependency>'
        payload += b'<groupId>a&amp;b</groupId><artifactId>c</artifactId>'
        payload += b'</dependency></dependencies></project>'

        assert pom_xml.parse_dependencies(payload)[0].group == 'a&b'


class TestPomModel:
    def test_coordinates_parent_properties_and_management_are_read_as_written(self) -> None:
        payload = f"""<?xml version="1.0"?>
        <project xmlns="{_POM_NAMESPACE}">
          <parent>
            <groupId>org.apache</groupId><artifactId>apache</artifactId><version>30</version>
          </parent>
          <artifactId>xmlsec</artifactId>
          <version>3.0.3</version>
          <properties>
            <slf4j.version>1.7.36</slf4j.version>
            <jetty.version>9.4.53.v20231009</jetty.version>
          </properties>
          <dependencyManagement>
            <dependencies>
              <dependency>
                <groupId>com.fasterxml.jackson</groupId><artifactId>jackson-bom</artifactId>
                <version>2.18.3</version><type>pom</type><scope>import</scope>
              </dependency>
            </dependencies>
          </dependencyManagement>
          <dependencies>
            <dependency>
              <groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId><version>${{slf4j.version}}</version>
            </dependency>
            <dependency>
              <groupId>org.eclipse.jetty</groupId><artifactId>jetty-server</artifactId>
              <version>${{jetty.version}}</version><scope>test</scope><optional>true</optional>
            </dependency>
          </dependencies>
        </project>""".encode()

        model = pom_xml.parse_model(payload)

        assert model is not None
        # inherited from the parent, so absent here: the resolver fills it in, the parser does not guess
        assert model.group is None
        assert (model.artifact, model.version) == ('xmlsec', '3.0.3')
        assert model.parent is not None
        assert model.parent.coordinate == 'org.apache:apache:30'
        assert model.properties == {'slf4j.version': '1.7.36', 'jetty.version': '9.4.53.v20231009'}
        assert [(d.coordinate_key, d.version, d.scope, d.type) for d in model.dependency_management] == [
            ('com.fasterxml.jackson:jackson-bom', '2.18.3', 'import', 'pom')
        ]
        # nothing interpolated, nothing filtered: every scope is kept for the resolver to weigh
        assert [(d.coordinate_key, d.version, d.scope, d.optional) for d in model.dependencies] == [
            ('org.slf4j:slf4j-api', '${slf4j.version}', None, False),
            ('org.eclipse.jetty:jetty-server', '${jetty.version}', 'test', True),
        ]

    def test_a_parent_missing_a_part_is_ignored(self) -> None:
        payload = b'<project><parent><groupId>g</groupId><artifactId>a</artifactId></parent></project>'

        model = pom_xml.parse_model(payload)

        assert model is not None
        assert model.parent is None

    def test_an_unsafe_document_has_no_model(self) -> None:
        assert pom_xml.parse_model(b'<!DOCTYPE x><project/>') is None
        assert pom_xml.parse_model(b'<project><dependencies>') is None
