soft_fail: False
scans:
  supported_scans:
    - secret
    - iac
    - sca
    - sast
  supported_sca_scans:
    - package-vulnerabilities
    - license-compliance
result_printer:
  lines_to_display: 3
  show_secret: False