name: Build and Publish pre-release

on:
  push:
    branches:
#      - main
      - "CM-22812-setup-pre-release-flow"

jobs:
  pre_release:
    name: Pre-Release
    runs-on: ubuntu-latest
    permissions:
      actions: write
#      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python - -y

    - name: Install Poetry Plugin
      run: pip install --no-cache-dir poetry-dynamic-versioning[plugin]

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Check Pre-Release Version
      id: check-version
      run: |
        echo "::debug::Package version: $(poetry version --short)"
        [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

    - name: Exit if not Pre-Release Version
      if: steps.check-version.outputs.prerelease != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}

    - name: Build package
      run: poetry build

# TODO
#    - name: Publish a Python distribution to PyPI
#      us]es: pypa/gh-action-pypi-publish@release/v1
